### ISSUE TITLE
question: 如何根据bytes创建jce struct

### ISSUE THREAD

**Issue by LxDebug** [yanyongyu/JceStruct#1]
遇到点困难希望得到您的帮助

**Comment by yanyongyu** [comment]
你可以直接在这里询问（

**Comment by LxDebug** [comment]
我要向腾讯小程序提交数据时 表单里的数据要转换成什么格式呢？下图是抓到的请求体
![BD7883FA-FDCD-43BC-B645-F333252646BD](https://user-images.githubusercontent.com/27006147/112094494-5594a800-8bd6-11eb-8196-326613868a39.png)

**Comment by LxDebug** [comment]
或者怎么使用您的项目提交像这样的数据

**Comment by yanyongyu** [comment]
这个请求看着并不像是jce格式

**Comment by yanyongyu** [comment]
能否复制一下hex数据，图片有点难以处理

**Comment by LxDebug** [comment]
![762209D0-EEC4-4E66-941F-06DF7AC0898F](https://user-images.githubusercontent.com/27006147/112156414-2fe0c080-8c21-11eb-9632-7326ab681095.jpeg)
0801122156315f4950485f4d494e4953444b5f312e31312e315f305f52454c454153455f421a8a016d6f64656c3d6950686f6e65266f733d694f532f31342e3426646973706c61793d3735302e3030303030302a313333342e303030303030266966613d30313045413746422d374445362d344635312d393436372d3444537453142303439354426696466613d42303237374132432d453539412d343144362d393132412d434134424642364643393346223a1236687474703a2f2f712e71712e636f6d2f612f73646b2f313131313435343935345f346130663364363f666c6f77547970653d6672656518002a1a286e756c6c295f303332313132323735303932385f373735З0З7З20d6d696е695f6170705f696е666f3a10476574417070496e666f42794c696e6b42e4010a0b313536383238383531313312c80165794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a7462324a70624755694f6949784e5459344d6a67344e5445784d794973496e427962794936496a41344e794973496d4e7064486b694f6949344e7a41694c434a705a434936496a6c6a5a4459794d6d49334d5441785a574d335a6a46684f475930596a5a6b59544d79596d51354d545a6b496e302e4433476d4c6a36704c4645546d477642345442387458535372454f5a727743356f6867627a57446b6c386b1a043230303120022a0032004a020802

**Comment by LxDebug** [comment]
数据是这样的 抓取于q.qq.com应该是jce

**Comment by LxDebug** [comment]
我这边自己写了一个jce体不知是否正确
a = {'1':username,'2':jwt,'3': '2001','4': 0,'5':'101794394'}
              busiBuff = {'0':'null','1':click,'2':fact,'3':'null','4': (nowtime / 1000) + n * 62,'5': 0,'6': 1,'7': 1001,'8': n * 62,'9': launchId1,'10':'','11': 0,'12':'null'}
              c = {'0': Seq,'1': 'V1_AND_MINISDK_1.5.3_0_RELEASE_B','2': deviceInfo,'3': busiBuff,'4': traceid,'5':'mini_app_growguard','6': 'JudgeTiming','7': a,'8':'null','9': 'null','10': 0}

**Comment by yanyongyu** [comment]
报错多半是因为哪里格式不正确，我再看看你的数据

**Comment by yanyongyu** [comment]
你的数据里是不是有非法字符，无法转换成bytes

![image](https://user-images.githubusercontent.com/42488585/112173996-062f9580-8c31-11eb-87a0-a83a92494abe.png)

**Comment by yanyongyu** [comment]
1044 1077

![image](https://user-images.githubusercontent.com/42488585/112175330-23189880-8c32-11eb-8a47-e2d5e41b4f0a.png)

**Comment by LxDebug** [comment]
是解决了嘛？

**Comment by yanyongyu** [comment]
你给的那串十六进制里面有非法字符

**Comment by yanyongyu** [comment]
由于数据不完整我无法给你提供更多帮助，先关闭issue，如果还有问题欢迎再次提出
